-- ============================================================================
-- 01_cargar_posiciones.sql - Carga del historico unificado de posiciones
-- Proyecto: DMujeres Tracking - FASE 3 parte 2
-- ============================================================================
-- Se ejecuta EN LA BASE NUEVA, con el staging ya cargado:
--   system.dmt_staging_posicion
-- (17 columnas legadas + fuente + es_mock). Lo llena 01_cargar_posiciones.sh
-- a partir del conjunto unificado deduplicado por (deviceid, fixtime) con
-- prioridad: traccar.tc_positions > tc_positions_bak_20260903 >
-- traccar_qa.tc_positions > dumps, ganando el mas reciente a igualdad.
--
-- Decisiones (ver docs/migration/HISTORICO-UNIFICADO.md):
--   * id legado -> tracking.dmt_posicion.id (GENERATED BY DEFAULT). El esquema
--     de FASE 3 parte 1 no tiene columna id_legado en dmt_posicion; el id
--     legado se conserva en id (03_tracking.sql).
--   * registrado_en = devicetime UTC (particionado); fijado_en = fixtime UTC;
--     recibido_en = servertime UTC. Las tres columnas legadas son iguales en
--     el 100 % del historico verificado.
--   * velocidad_kmh = speed * 1.852 (Traccar guarda nudos).
--   * bateria_pct = atributos->>'batteryLevel'.
--   * valida = valid AND NOT es_mock (y fixtime dentro de [2026-01-01, now]).
--   * Idempotencia: ON CONFLICT (dispositivo_id, registrado_en, id) DO NOTHING
--     contra el indice unico uq_dmt_posicion_migracion.
--   * Cada lote se registra en system.dmt_migracion_mapa.
--
-- Tamano de lote: GUC dmt.batch_size (por defecto 5000).
--   PGOPTIONS="-c dmt.batch_size=5000" psql ... -f 01_cargar_posiciones.sql
-- ============================================================================

\set ON_ERROR_STOP on
BEGIN;

-- ---------------------------------------------------------------------------
-- 1) Particion 2026-08 (el historico legado arranca el 2026-08-17)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tracking.dmt_posicion_2026_08
    PARTITION OF tracking.dmt_posicion
    FOR VALUES FROM ('2026-08-01 00:00:00+00') TO ('2026-09-01 00:00:00+00');

-- ---------------------------------------------------------------------------
-- 2) Staging del conjunto unificado
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system.dmt_staging_posicion (
    id_legado   integer      NOT NULL,
    deviceid    integer      NOT NULL,
    protocol    varchar(128),
    servertime  timestamp,
    devicetime  timestamp,
    fixtime     timestamp,
    valid       boolean,
    latitude    double precision,
    longitude   double precision,
    altitude    double precision,
    speed       double precision,
    course      double precision,
    address     varchar(512),
    attributes  varchar(4000),
    accuracy    double precision,
    network     varchar(4000),
    geofenceids varchar(128),
    fuente      text,
    es_mock     boolean      NOT NULL DEFAULT false
);

-- ---------------------------------------------------------------------------
-- 3) Utilitario JSON defensivo (texto -> jsonb sin abortar la carga)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION system.dmt_jsonb_seguro(p_texto text)
RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE
AS $fn$
BEGIN
    IF p_texto IS NULL OR btrim(p_texto) = '' THEN
        RETURN '{}'::jsonb;
    END IF;
    RETURN p_texto::jsonb;
EXCEPTION WHEN others THEN
    RETURN jsonb_build_object('crudo', p_texto);
END;
$fn$;

COMMENT ON FUNCTION system.dmt_jsonb_seguro(text) IS
    'Convierte attributes legado a JSONB; si no es JSON valido lo conserva como {"crudo": ...} para no perder el dato.';

-- ---------------------------------------------------------------------------
-- 4) Indice unico para la idempotencia
--    (en tabla particionada debe incluir la columna de particionado)
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS uq_dmt_posicion_migracion
    ON tracking.dmt_posicion (dispositivo_id, registrado_en, id);

-- ---------------------------------------------------------------------------
-- 5) Precondicion: todos los dispositivos del staging deben existir
-- ---------------------------------------------------------------------------
DO $pre$
DECLARE
    v_faltantes integer;
BEGIN
    SELECT count(DISTINCT s.deviceid)
      INTO v_faltantes
      FROM system.dmt_staging_posicion s
      LEFT JOIN tracking.dmt_dispositivo d ON d.id_legado = s.deviceid
     WHERE d.id IS NULL;

    IF v_faltantes > 0 THEN
        RAISE EXCEPTION
            'Hay % dispositivos legados sin fila en tracking.dmt_dispositivo (id_legado). Migrar dispositivos antes de las posiciones.',
            v_faltantes;
    END IF;
END
$pre$;

-- ---------------------------------------------------------------------------
-- 6) Carga por lotes con registro en system.dmt_migracion_mapa
-- ---------------------------------------------------------------------------
DO $etl$
DECLARE
    v_batch integer := coalesce(
        nullif(current_setting('dmt.batch_size', true), '')::integer, 5000);
    v_min   integer;
    v_max   integer;
    v_lote  integer := 0;
    v_filas bigint;
    v_total bigint := 0;
BEGIN
    SELECT min(id_legado), max(id_legado)
      INTO v_min, v_max
      FROM system.dmt_staging_posicion;

    IF v_min IS NULL THEN
        RAISE EXCEPTION 'system.dmt_staging_posicion esta vacia: nada que cargar';
    END IF;

    RAISE NOTICE 'ETL posiciones: % filas en staging, id_legado %..%, lote de %',
        (SELECT count(*) FROM system.dmt_staging_posicion), v_min, v_max, v_batch;

    WHILE v_min <= v_max LOOP
        v_lote := v_lote + 1;

        INSERT INTO tracking.dmt_posicion (
            id, dispositivo_id, protocolo, latitud, longitud, altitud_m,
            velocidad_kmh, rumbo_grados, precision_m, bateria_pct, valida,
            direccion, red, geocercas, fijado_en, registrado_en, recibido_en,
            atributos
        )
        SELECT
            s.id_legado,
            d.id,
            nullif(s.protocol, ''),
            s.latitude,
            s.longitude,
            s.altitude,
            (s.speed * 1.852)::real,
            s.course::real,
            s.accuracy::real,
            CASE
                WHEN (system.dmt_jsonb_seguro(s.attributes) ->> 'batteryLevel')
                     ~ '^-?[0-9]+(\.[0-9]+)?$'
                THEN (system.dmt_jsonb_seguro(s.attributes) ->> 'batteryLevel')::real
            END,
            coalesce(s.valid, true)
              AND NOT s.es_mock
              AND s.fixtime >= TIMESTAMP '2026-01-01 00:00:00'
              AND s.fixtime <= (now() AT TIME ZONE 'America/Guayaquil'),
            nullif(s.address, ''),
            nullif(s.network, ''),
            nullif(s.geofenceids, ''),
            (s.fixtime AT TIME ZONE 'America/Guayaquil'),
            (s.devicetime AT TIME ZONE 'America/Guayaquil'),
            (s.servertime AT TIME ZONE 'America/Guayaquil'),
            system.dmt_jsonb_seguro(s.attributes)
              || CASE WHEN s.es_mock
                      THEN jsonb_build_object('migracion',
                               jsonb_build_object('mock', true, 'fuente', s.fuente))
                      ELSE '{}'::jsonb
                 END
        FROM system.dmt_staging_posicion s
        JOIN tracking.dmt_dispositivo d ON d.id_legado = s.deviceid
        WHERE s.id_legado >= v_min
          AND s.id_legado <  v_min + v_batch
        ON CONFLICT (dispositivo_id, registrado_en, id) DO NOTHING;

        GET DIAGNOSTICS v_filas = ROW_COUNT;
        v_total := v_total + v_filas;

        INSERT INTO system.dmt_migracion_mapa (
            tabla_origen, id_origen, tabla_destino, esquema_destino, nota
        )
        VALUES (
            'traccar.public.tc_positions',
            'lote:' || v_lote || ':' || v_min || '-' || (v_min + v_batch - 1),
            'tracking.dmt_posicion',
            'tracking',
            format('lote %s: %s filas insertadas (id_legado %s..%s)',
                   v_lote, v_filas, v_min, v_min + v_batch - 1)
        )
        ON CONFLICT (tabla_origen, id_origen) DO UPDATE
            SET nota = EXCLUDED.nota,
                migrado_en = now();

        v_min := v_min + v_batch;
    END LOOP;

    RAISE NOTICE 'ETL posiciones: % filas nuevas insertadas en % lotes (idempotente: re-ejecutar no duplica)',
        v_total, v_lote;
END
$etl$;

COMMIT;
