-- ============================================================================
-- 03_ajustar_secuencias.sql - setval de secuencias con ids legados
-- Proyecto: DMujeres Tracking - FASE 3 parte 3
-- ============================================================================
-- Tablas cuyo id conserva el id legado (GENERATED BY DEFAULT): si no se
-- reajusta la secuencia, las inserciones nuevas de la plataforma chocarian
-- con ids ya usados. Se ejecuta EN LA BASE NUEVA despues de todas las cargas.
-- Idempotente.
-- ============================================================================

\set ON_ERROR_STOP on
BEGIN;

SELECT setval(pg_get_serial_sequence('iam.dmt_usuario', 'id'),
              (SELECT coalesce(max(id), 1) FROM iam.dmt_usuario),
              (SELECT max(id) IS NOT NULL FROM iam.dmt_usuario));

SELECT setval(pg_get_serial_sequence('tracking.dmt_dispositivo', 'id'),
              (SELECT coalesce(max(id), 1) FROM tracking.dmt_dispositivo),
              (SELECT max(id) IS NOT NULL FROM tracking.dmt_dispositivo));

SELECT setval(pg_get_serial_sequence('tracking.dmt_posicion', 'id'),
              (SELECT coalesce(max(id), 1) FROM tracking.dmt_posicion),
              (SELECT max(id) IS NOT NULL FROM tracking.dmt_posicion));

SELECT setval(pg_get_serial_sequence('tracking.dmt_evento', 'id'),
              (SELECT coalesce(max(id), 1) FROM tracking.dmt_evento),
              (SELECT max(id) IS NOT NULL FROM tracking.dmt_evento));

COMMIT;

SELECT 'iam.dmt_usuario' AS tabla, last_value AS secuencia FROM iam.dmt_usuario_id_seq
UNION ALL SELECT 'tracking.dmt_dispositivo', last_value FROM tracking.dmt_dispositivo_id_seq
UNION ALL SELECT 'tracking.dmt_posicion', last_value FROM tracking.dmt_posicion_id_seq
UNION ALL SELECT 'tracking.dmt_evento', last_value FROM tracking.dmt_evento_id_seq
ORDER BY 1;
