# Configuración básica de Nginx para Dmujeres-Traccar
proxy_cache_path /var/cache/nginx/google_tiles levels=1:2 keys_zone=google_tiles_cache:10m max_size=5g inactive=30d use_temp_path=off;

server {
    listen 80;
    server_name localhost;

    location / {
        root /home/Dmujeres-Traccar/frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8082;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    location /google-tiles {
        proxy_pass https://mt1.google.com/vt;
        proxy_set_header Host mt1.google.com;
        proxy_cache google_tiles_cache;
        proxy_cache_valid 200 302 30d;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        proxy_pass_request_headers off;
        proxy_hide_header Set-Cookie;
        proxy_ignore_headers Set-Cookie Cache-Control Expires;
    }
}

