-- ============================================================================
-- 02_iam.sql - Identidad, roles, sesiones y credenciales de la App
-- Proyecto: DMujeres Tracking - nomenclatura dmt_
-- ============================================================================
-- Origen legado principal: tc_users, tc_keystore, tc_revoked_tokens,
-- tc_fcm_tokens.
--
-- Compatibilidad con la App en operacion:
--   * dmt_usuario.id_legado conserva el id de tc_users.
--   * dmt_usuario.hash_clave / sal conservan hashedpassword / salt para
--     poder verificar las credenciales existentes sin pedir cambio de clave.
--   * dmt_clave_firma conserva el par de tc_keystore: los tokens JWT ya
--     emitidos a la App deben seguir siendo validos durante el corte.
--   * dmt_sesion.dispositivo_id se referencia en 08_indices.sql porque la
--     tabla tracking.dmt_dispositivo se crea despues de este archivo.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Usuarios
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_usuario (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico        UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado         BIGINT,
    nombre_usuario    TEXT,
    nombre            TEXT        NOT NULL,
    correo            TEXT,
    telefono          TEXT,
    hash_clave        TEXT,
    sal               TEXT,
    habilitado        BOOLEAN     NOT NULL DEFAULT TRUE,
    administrador     BOOLEAN     NOT NULL DEFAULT FALSE,
    solo_lectura      BOOLEAN     NOT NULL DEFAULT FALSE,
    clave_totp        TEXT,
    expira_en         TIMESTAMPTZ,
    ultimo_acceso_en  TIMESTAMPTZ,
    atributos         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_usuario PRIMARY KEY (id),
    CONSTRAINT uq_dmt_usuario_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_usuario_legado UNIQUE (id_legado),
    CONSTRAINT uq_dmt_usuario_nombre_usuario UNIQUE (nombre_usuario)
);

COMMENT ON TABLE iam.dmt_usuario IS
    'Cuenta de acceso. id_legado = tc_users.id; hash_clave/sal permiten validar credenciales heredadas.';
COMMENT ON COLUMN iam.dmt_usuario.nombre_usuario IS
    'Login de la App/web (legado tc_users.login).';
COMMENT ON COLUMN iam.dmt_usuario.hash_clave IS
    'Hash PBKDF2 del motor legado (tc_users.hashedpassword). No se regenera durante la migracion.';
COMMENT ON COLUMN iam.dmt_usuario.sal IS
    'Sal de la credencial heredada (tc_users.salt). Permite doble verificacion durante el corte.';
COMMENT ON COLUMN iam.dmt_usuario.solo_lectura IS
    'Usuario de solo consulta (legado tc_users.readonly).';
COMMENT ON COLUMN iam.dmt_usuario.clave_totp IS
    'Secreto TOTP de doble factor (legado tc_users.totpkey). Dato sensible: no registrar en logs.';

-- ---------------------------------------------------------------------------
-- Roles
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_rol (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    codigo         TEXT        NOT NULL,
    nombre         TEXT        NOT NULL,
    descripcion    TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_rol PRIMARY KEY (id),
    CONSTRAINT uq_dmt_rol_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_rol_codigo UNIQUE (codigo)
);

COMMENT ON TABLE iam.dmt_rol IS
    'Catalogo de roles de la plataforma nueva (admin, operador, consulta, etc.).';

-- ---------------------------------------------------------------------------
-- Roles por usuario
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_usuario_rol (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    usuario_id     BIGINT      NOT NULL,
    rol_id         BIGINT      NOT NULL,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_usuario_rol PRIMARY KEY (id),
    CONSTRAINT uq_dmt_usuario_rol_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_usuario_rol UNIQUE (usuario_id, rol_id),
    CONSTRAINT fk_dmt_usuario_rol_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_dmt_usuario_rol_rol FOREIGN KEY (rol_id)
        REFERENCES iam.dmt_rol (id) ON DELETE CASCADE
);

COMMENT ON TABLE iam.dmt_usuario_rol IS
    'Asignacion de roles. Los permisos de manager/subordinado de tc_user_user quedan como evaluacion de migracion.';

-- ---------------------------------------------------------------------------
-- Sesiones
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_sesion (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    usuario_id     BIGINT      NOT NULL,
    dispositivo_id BIGINT,
    token_hash     TEXT        NOT NULL,
    tipo           TEXT        NOT NULL DEFAULT 'web',
    direccion_ip   INET,
    agente         TEXT,
    iniciada_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    expira_en      TIMESTAMPTZ,
    revocada_en    TIMESTAMPTZ,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_sesion PRIMARY KEY (id),
    CONSTRAINT uq_dmt_sesion_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_sesion_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_dmt_sesion_tipo CHECK (tipo IN ('web', 'movil', 'api')),
    CONSTRAINT fk_dmt_sesion_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE CASCADE
);

COMMENT ON TABLE iam.dmt_sesion IS
    'Sesiones de la plataforma nueva. token_hash nunca guarda el token en claro.';
COMMENT ON COLUMN iam.dmt_sesion.dispositivo_id IS
    'Dispositivo movil asociado; FK fk_dmt_sesion_dispositivo se crea en 08_indices.sql.';

-- ---------------------------------------------------------------------------
-- Tokens FCM (continuidad de notificaciones de la App)
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_token_fcm (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    dispositivo_id BIGINT      NOT NULL,
    token          TEXT        NOT NULL,
    token_previo   TEXT,
    activo         BOOLEAN     NOT NULL DEFAULT TRUE,
    invalido       BOOLEAN     NOT NULL DEFAULT FALSE,
    ultimo_uso_en  TIMESTAMPTZ,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_token_fcm PRIMARY KEY (id),
    CONSTRAINT uq_dmt_token_fcm_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_token_fcm_token UNIQUE (token)
);

COMMENT ON TABLE iam.dmt_token_fcm IS
    'Token de notificaciones FCM por dispositivo (legado tc_fcm_tokens). El contrato FCM de la App no cambia.';

-- ---------------------------------------------------------------------------
-- Claves de firma de tokens (compatibilidad de credenciales de la App)
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_clave_firma (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    clave_publica  BYTEA       NOT NULL,
    clave_privada  BYTEA       NOT NULL,
    activa         BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_clave_firma PRIMARY KEY (id),
    CONSTRAINT uq_dmt_clave_firma_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_clave_firma_legado UNIQUE (id_legado)
);

COMMENT ON TABLE iam.dmt_clave_firma IS
    'Par de claves de firma JWT (legado tc_keystore). Conservarlo evita invalidar los tokens vigentes de la App en el cutover.';
COMMENT ON COLUMN iam.dmt_clave_firma.clave_privada IS
    'Material secreto: la migracion no debe registrarlo en logs ni volcarlo a documentacion.';

-- ---------------------------------------------------------------------------
-- Tokens revocados (lista negra de JWT heredados)
-- ---------------------------------------------------------------------------
CREATE TABLE iam.dmt_token_revocado (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    token_hash     TEXT        NOT NULL,
    expira_en      TIMESTAMPTZ,
    revocado_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    motivo         TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_token_revocado PRIMARY KEY (id),
    CONSTRAINT uq_dmt_token_revocado_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_token_revocado_token_hash UNIQUE (token_hash),
    CONSTRAINT uq_dmt_token_revocado_legado UNIQUE (id_legado)
);

COMMENT ON TABLE iam.dmt_token_revocado IS
    'Lista negra de tokens heredados (legado tc_revoked_tokens). Guarda hash, no el token en claro.';

COMMIT;
