-- ============================================================================
-- 04_telemetry.sql - Muestras de alta frecuencia y salud del dispositivo
-- Proyecto: DMujeres Tracking - nomenclatura dmt_
-- ============================================================================
-- Origen legado:
--   * tc_device_health          -> telemetry.dmt_salud_dispositivo
--   * atributos de posicion      -> telemetry.dmt_bateria / dmt_senal
--   * tc_attributes / tc_device_attribute (definiciones) -> evaluar; no se
--     copian como muestras (0 filas en produccion).
--
-- La telemetria flexible vive en JSONB (`atributos`), pero las columnas que
-- se filtran o grafican (porcentaje, senal, tiempo) son propias e indexadas.
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Bateria
-- ---------------------------------------------------------------------------
CREATE TABLE telemetry.dmt_bateria (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    dispositivo_id BIGINT      NOT NULL,
    porcentaje     REAL,
    cargando       BOOLEAN,
    voltaje_v      REAL,
    temperatura_c  REAL,
    registrado_en  TIMESTAMPTZ NOT NULL,
    recibido_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    atributos      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_bateria PRIMARY KEY (id),
    CONSTRAINT uq_dmt_bateria_publico UNIQUE (id_publico),
    CONSTRAINT ck_dmt_bateria_porcentaje CHECK (porcentaje IS NULL OR (porcentaje >= 0 AND porcentaje <= 100)),
    CONSTRAINT fk_dmt_bateria_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id) ON DELETE CASCADE
);

COMMENT ON TABLE telemetry.dmt_bateria IS
    'Muestras de bateria. Origen legado: atributos batteryLevel / charge de las posiciones OsmAnd.';
COMMENT ON COLUMN telemetry.dmt_bateria.porcentaje IS
    'Nivel de bateria 0-100 (legado atributos->>batteryLevel).';
COMMENT ON COLUMN telemetry.dmt_bateria.cargando IS
    'Indicador de carga (legado atributos->>charge).';

-- ---------------------------------------------------------------------------
-- Senal / red
-- ---------------------------------------------------------------------------
CREATE TABLE telemetry.dmt_senal (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    dispositivo_id BIGINT      NOT NULL,
    tipo           TEXT        NOT NULL,
    valor          NUMERIC,
    unidad         TEXT,
    calidad        TEXT,
    registrado_en  TIMESTAMPTZ NOT NULL,
    recibido_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    atributos      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_senal PRIMARY KEY (id),
    CONSTRAINT uq_dmt_senal_publico UNIQUE (id_publico),
    CONSTRAINT ck_dmt_senal_tipo CHECK (tipo IN ('red', 'gps', 'mqtt', 'app', 'otra')),
    CONSTRAINT fk_dmt_senal_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id) ON DELETE CASCADE
);

COMMENT ON TABLE telemetry.dmt_senal IS
    'Muestras de senal/estado de red (netState, mqttState, gpsState del diagnostico de la App y del protocolo).';

-- ---------------------------------------------------------------------------
-- Salud del dispositivo
-- ---------------------------------------------------------------------------
CREATE TABLE telemetry.dmt_salud_dispositivo (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico         UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado          BIGINT,
    dispositivo_id     BIGINT      NOT NULL,
    fabricante         TEXT,
    modelo             TEXT,
    version_android    TEXT,
    version_app        TEXT,
    estado_salud       TEXT,
    primer_plano       BOOLEAN,
    pantalla_encendida BOOLEAN,
    movimiento         TEXT,
    red                TEXT,
    cola_salida        INTEGER,
    ultimo_fix_en      TIMESTAMPTZ,
    preparacion        TEXT,
    continuidad        TEXT,
    causa_continuidad  TEXT,
    recuperacion       TEXT,
    sesion_id          TEXT,
    duracion_ms        BIGINT,
    tipo_evento        TEXT,
    motivo             TEXT,
    franja_wall        BIGINT,
    registrado_en      TIMESTAMPTZ NOT NULL,
    recibido_en        TIMESTAMPTZ NOT NULL DEFAULT now(),
    atributos          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en          TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_salud_dispositivo PRIMARY KEY (id),
    CONSTRAINT uq_dmt_salud_dispositivo_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_salud_dispositivo_legado UNIQUE (id_legado),
    CONSTRAINT fk_dmt_salud_dispositivo_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id) ON DELETE CASCADE
);

COMMENT ON TABLE telemetry.dmt_salud_dispositivo IS
    'Buckets de salud del dispositivo (legado tc_device_health). Conserva id_legado para trazabilidad de la App.';
COMMENT ON COLUMN telemetry.dmt_salud_dispositivo.registrado_en IS
    'Legado tc_device_health.ts (UTC).';
COMMENT ON COLUMN telemetry.dmt_salud_dispositivo.primer_plano IS
    'Servicio en primer plano (legado fgs).';
COMMENT ON COLUMN telemetry.dmt_salud_dispositivo.cola_salida IS
    'Mensajes pendientes en la cola de salida (legado outbox).';
COMMENT ON COLUMN telemetry.dmt_salud_dispositivo.franja_wall IS
    'Bucket temporal del reloj de pared (legado wallbucket).';
COMMENT ON COLUMN telemetry.dmt_salud_dispositivo.atributos IS
    'JSONB flexible; el legado ya lo almacena como jsonb con el embudo funnel del diagnostico.';

COMMIT;
