-- ============================================================================
-- 05_operations.sql - Jornadas, tramos, asignaciones y alertas
-- Proyecto: DMujeres Tracking - nomenclatura dmt_
-- ============================================================================
-- Origen legado:
--   * tc_user_device     -> operations.dmt_asignacion
--   * tc_recovery_event  -> operations.dmt_alerta (origen 'recuperacion')
--   * tc_mobile_messages -> operations.dmt_alerta (origen 'movil', evaluar:
--     la cola/lease es efimera; se decide en la migracion)
--   * jornadas y tramos son datos nuevos que produce la plataforma; no
--     existen en el legado (se derivan del historico de posiciones).
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Jornadas
-- ---------------------------------------------------------------------------
CREATE TABLE operations.dmt_jornada (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico         UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado          BIGINT,
    dispositivo_id     BIGINT      NOT NULL,
    usuario_id         BIGINT,
    inicio_en          TIMESTAMPTZ NOT NULL,
    fin_en             TIMESTAMPTZ,
    estado             TEXT        NOT NULL DEFAULT 'abierta',
    distancia_km       REAL,
    duracion_s         BIGINT,
    bateria_inicio_pct REAL,
    bateria_fin_pct    REAL,
    atributos          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en          TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_jornada PRIMARY KEY (id),
    CONSTRAINT uq_dmt_jornada_publico UNIQUE (id_publico),
    CONSTRAINT ck_dmt_jornada_estado CHECK (estado IN ('abierta', 'cerrada', 'anulada')),
    CONSTRAINT fk_dmt_jornada_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id),
    CONSTRAINT fk_dmt_jornada_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id)
);

COMMENT ON TABLE operations.dmt_jornada IS
    'Jornada de trabajo por dispositivo/usuario. Dato nuevo de la plataforma, derivable del historico de posiciones.';

-- ---------------------------------------------------------------------------
-- Tramos de jornada
-- ---------------------------------------------------------------------------
CREATE TABLE operations.dmt_jornada_tramo (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico             UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado              BIGINT,
    jornada_id             BIGINT      NOT NULL,
    tipo                   TEXT        NOT NULL,
    inicio_en              TIMESTAMPTZ NOT NULL,
    fin_en                 TIMESTAMPTZ,
    distancia_km           REAL,
    duracion_s             BIGINT,
    velocidad_promedio_kmh REAL,
    velocidad_maxima_kmh   REAL,
    latitud_inicio         DOUBLE PRECISION,
    longitud_inicio        DOUBLE PRECISION,
    latitud_fin            DOUBLE PRECISION,
    longitud_fin           DOUBLE PRECISION,
    atributos              JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en              TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en         TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_jornada_tramo PRIMARY KEY (id),
    CONSTRAINT uq_dmt_jornada_tramo_publico UNIQUE (id_publico),
    CONSTRAINT ck_dmt_jornada_tramo_tipo CHECK (tipo IN ('movimiento', 'pausa', 'sin_senal')),
    CONSTRAINT fk_dmt_jornada_tramo_jornada FOREIGN KEY (jornada_id)
        REFERENCES operations.dmt_jornada (id) ON DELETE CASCADE
);

COMMENT ON TABLE operations.dmt_jornada_tramo IS
    'Tramos movimiento/pausa/sin senal dentro de una jornada; alimenta reportes y replay segmentado.';

-- ---------------------------------------------------------------------------
-- Asignaciones usuario-dispositivo
-- ---------------------------------------------------------------------------
CREATE TABLE operations.dmt_asignacion (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    usuario_id     BIGINT      NOT NULL,
    dispositivo_id BIGINT      NOT NULL,
    desde_en       TIMESTAMPTZ NOT NULL DEFAULT now(),
    hasta_en       TIMESTAMPTZ,
    activa         BOOLEAN     NOT NULL DEFAULT TRUE,
    atributos      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_asignacion PRIMARY KEY (id),
    CONSTRAINT uq_dmt_asignacion_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_asignacion_periodo UNIQUE (usuario_id, dispositivo_id, desde_en),
    CONSTRAINT fk_dmt_asignacion_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE CASCADE,
    CONSTRAINT fk_dmt_asignacion_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id) ON DELETE CASCADE
);

COMMENT ON TABLE operations.dmt_asignacion IS
    'Asignacion usuario-dispositivo (legado tc_user_device, par userid+deviceid). Permite historial con desde_en/hasta_en.';

-- ---------------------------------------------------------------------------
-- Alertas
-- ---------------------------------------------------------------------------
CREATE TABLE operations.dmt_alerta (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    origen         TEXT        NOT NULL DEFAULT 'recuperacion',
    dispositivo_id BIGINT,
    usuario_id     BIGINT,
    tipo           TEXT        NOT NULL,
    subtipo        TEXT,
    severidad      TEXT        NOT NULL DEFAULT 'media',
    estado         TEXT        NOT NULL DEFAULT 'nueva',
    mensaje        TEXT,
    ocurrido_en    TIMESTAMPTZ NOT NULL,
    reconocida_en  TIMESTAMPTZ,
    resuelta_en    TIMESTAMPTZ,
    atributos      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_alerta PRIMARY KEY (id),
    CONSTRAINT uq_dmt_alerta_publico UNIQUE (id_publico),
    CONSTRAINT ck_dmt_alerta_origen CHECK (origen IN ('recuperacion', 'movil', 'regla', 'sistema')),
    CONSTRAINT ck_dmt_alerta_estado CHECK (estado IN ('nueva', 'reconocida', 'resuelta', 'descartada')),
    CONSTRAINT fk_dmt_alerta_dispositivo FOREIGN KEY (dispositivo_id)
        REFERENCES tracking.dmt_dispositivo (id) ON DELETE SET NULL,
    CONSTRAINT fk_dmt_alerta_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE SET NULL
);

COMMENT ON TABLE operations.dmt_alerta IS
    'Alertas operativas. Agrupa recuperacion (tc_recovery_event) y mensajeria movil (tc_mobile_messages) por origen; detalles variables en atributos.';
COMMENT ON COLUMN operations.dmt_alerta.id_legado IS
    'Id en la tabla de origen indicada por `origen`; la unicidad por par se refuerza en 08_indices.sql.';

COMMIT;
