-- ============================================================================
-- 06_audit.sql - Trazabilidad administrativa
-- Proyecto: DMujeres Tracking - nomenclatura dmt_
-- ============================================================================
-- Origen legado: tc_actions (1517 filas en produccion al 2026-09-25:
-- report, login, link/device, create/device, denied, logout, etc.).
--
-- dmt_auditoria guarda el "quien hizo que sobre que". No se usa JSONB como
-- sustituto del modelo: accion/entidad/tiempo son columnas indexadas y el
-- detalle variable queda en `datos`.
-- ============================================================================

BEGIN;

CREATE TABLE audit.dmt_auditoria (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    id_legado      BIGINT,
    usuario_id     BIGINT,
    accion         TEXT        NOT NULL,
    entidad        TEXT,
    entidad_id     TEXT,
    descripcion    TEXT,
    datos          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    direccion      TEXT,
    agente         TEXT,
    ocurrido_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_auditoria PRIMARY KEY (id),
    CONSTRAINT uq_dmt_auditoria_publico UNIQUE (id_publico),
    CONSTRAINT fk_dmt_auditoria_usuario FOREIGN KEY (usuario_id)
        REFERENCES iam.dmt_usuario (id) ON DELETE SET NULL
);

COMMENT ON TABLE audit.dmt_auditoria IS
    'Bitacora de acciones administrativas y de seguridad (legado tc_actions). Solo insercion desde la API.';
COMMENT ON COLUMN audit.dmt_auditoria.accion IS
    'Accion realizada (legado tc_actions.actiontype): login, report, create, edit, remove, link, denied, logout...';
COMMENT ON COLUMN audit.dmt_auditoria.entidad IS
    'Objeto afectado (legado tc_actions.objecttype): device, user, ...';
COMMENT ON COLUMN audit.dmt_auditoria.entidad_id IS
    'Id textual del objeto afectado (legado tc_actions.objectid).';
COMMENT ON COLUMN audit.dmt_auditoria.direccion IS
    'Direccion de origen en texto (legado tc_actions.address); se conserva TEXT porque el legado no siempre trae una IP valida.';
COMMENT ON COLUMN audit.dmt_auditoria.datos IS
    'Detalle variable de la accion (legado tc_actions.attributes, texto con JSON).';

COMMIT;
