-- ============================================================================
-- 07_system.sql - Configuracion, mapa de migracion y version del esquema
-- Proyecto: DMujeres Tracking - nomenclatura dmt_
-- ============================================================================
-- system.dmt_migracion_mapa materializa el diccionario legado->nuevo de
-- docs/database/MAPA-LEGADO-DMT.md: una fila por objeto migrado.
--
-- dmt_version_esquema registra que archivos de database/schema/ se aplicaron
-- y con que checksum (el checksum se calcula al desplegar; no se fija aqui).
-- ============================================================================

BEGIN;

-- ---------------------------------------------------------------------------
-- Configuracion
-- ---------------------------------------------------------------------------
CREATE TABLE system.dmt_configuracion (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    clave          TEXT        NOT NULL,
    valor          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    descripcion    TEXT,
    es_secreto     BOOLEAN     NOT NULL DEFAULT FALSE,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_configuracion PRIMARY KEY (id),
    CONSTRAINT uq_dmt_configuracion_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_configuracion_clave UNIQUE (clave)
);

COMMENT ON TABLE system.dmt_configuracion IS
    'Parametros de la plataforma nueva. es_secreto=TRUE indica que el valor no debe exponerse por API ni en logs.';

-- ---------------------------------------------------------------------------
-- Mapa de migracion legado -> nuevo
-- ---------------------------------------------------------------------------
CREATE TABLE system.dmt_migracion_mapa (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    tabla_origen   TEXT        NOT NULL,
    id_origen      TEXT        NOT NULL,
    tabla_destino  TEXT,
    id_destino     BIGINT,
    esquema_destino TEXT,
    migrado_en     TIMESTAMPTZ NOT NULL DEFAULT now(),
    nota           TEXT,
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_migracion_mapa PRIMARY KEY (id),
    CONSTRAINT uq_dmt_migracion_mapa_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_migracion_mapa_par UNIQUE (tabla_origen, id_origen)
);

COMMENT ON TABLE system.dmt_migracion_mapa IS
    'Una fila por objeto migrado. id_origen es TEXT para admitir claves simples (tc_users.id) y compuestas (tc_user_device: userid:deviceid).';
COMMENT ON COLUMN system.dmt_migracion_mapa.tabla_origen IS
    'Nombre legado completo, por ejemplo traccar.public.tc_positions.';
COMMENT ON COLUMN system.dmt_migracion_mapa.id_destino IS
    'id de la fila en la tabla destino (BIGINT de la plataforma nueva).';

-- ---------------------------------------------------------------------------
-- Version del esquema
-- ---------------------------------------------------------------------------
CREATE TABLE system.dmt_version_esquema (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_publico     UUID        NOT NULL DEFAULT system.uuidv7(),
    version        TEXT        NOT NULL,
    archivo        TEXT,
    checksum       TEXT,
    descripcion    TEXT,
    aplicado_en    TIMESTAMPTZ NOT NULL DEFAULT now(),
    creado_en      TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_dmt_version_esquema PRIMARY KEY (id),
    CONSTRAINT uq_dmt_version_esquema_publico UNIQUE (id_publico),
    CONSTRAINT uq_dmt_version_esquema_version UNIQUE (version)
);

COMMENT ON TABLE system.dmt_version_esquema IS
    'Registro de aplicacion de los archivos database/schema/*.sql (version, archivo, sha256 opcional).';

COMMIT;
